baseURL = "https://blog.cruru.kr/blog/"
languageCode = "ko-kr"
title = "Team Cruru's Develop Blog"

[module]
[[module.imports]]
path = "github.com/colinwilson/lotusdocs"
disable = false
[[module.imports]]
path = "github.com/gohugoio/hugo-mod-bootstrap-scss/v5"
disable = false

[frontmatter]
    author = ['authors']
    series = ['series']
    categories = ['categories']
    date = ['date']

[menu]
[[menu.primary]]
name = "Infra"
url = "/blog/docs/infra/"
identifier = "docs"
weight = 10

[[menu.primary]]
name = "Backend"
url = "/blog/docs/backend/"
identifier = "showcase"
weight = 20

[[menu.primary]]
name = "Frontend"
url = "/blog/docs/frontend/"
identifier = "community"
weight = 30

[params.social]
github = 'woowacourse-teams/2024-cruru'

[params.docs]
pathName = 'docs'
themeColor = 'magenta'
prismTheme = 'lucario'

[params.footer]
copyright = '© :YEAR: 우아한테크코스 Cruru. Built with [**Lotus Docs**](https://github.com/colinwilson/lotusdocs)'

[markup.goldmark.renderer]
unsafe = true
